(()=>{
const cfg={apiKey:"AIzaSyCpEKb8mi6SOtCf1VUTwt79XTkRxhBBlko",authDomain:"proyek1-475304.firebaseapp.com",projectId:"proyek1-475304",storageBucket:"proyek1-475304.firebasestorage.app",messagingSenderId:"705620835425",appId:"1:705620835425:web:3c691e0e12add3b62cbe20"};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],key=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'),parse=s=>{const a=s.split('-').map(Number);return new Date(a[0],a[1]-1,a[2])},id=()=>crypto.randomUUID?.()||Date.now().toString(36),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const K={tasks:'taskku_schedules_v2',routines:'taskku_routines_v1',done:'taskku_daily_checks_v2',notes:'taskku_notes_v2'},read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},local=()=>{localStorage.setItem(K.tasks,JSON.stringify(tasks));localStorage.setItem(K.routines,JSON.stringify(routines));localStorage.setItem(K.done,JSON.stringify(done));localStorage.setItem(K.notes,JSON.stringify(notes))};
let tasks=read(K.tasks,[]),routines=read(K.routines,[]),done=read(K.done,{}),notes=read(K.notes,[]),date=new Date(),month=new Date(date.getFullYear(),date.getMonth(),1),page='today',filter=null,editTask=null,cloudReady=false,applying=false,timer,installPrompt;
const colors={Sekolah:'var(--school,#386fd0)',Konten:'var(--content,#9a5598)',Rumah:'var(--home,#bf6f23)',Lainnya:'var(--muted)'},icons={Sekolah:'school',Konten:'videocam',Rumah:'home',Lainnya:'push_pin'};
const cloud=firebase.firestore(firebase.initializeApp(cfg)).collection('taskku').doc('data');
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function save(){local();if(cloudReady&&!applying){clearTimeout(timer);timer=setTimeout(()=>cloud.set({tasks,routines,done,notes,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}).then(()=>$('#syncText').textContent='Tersinkron Firebase').catch(()=>toast('Sinkronisasi gagal. Periksa internet.')),250)}}
function occurs(t,d){return t.kind==='weekly'?(t.days||[]).includes(d.getDay()):t.date===key(d)}function dayTasks(d){return tasks.filter(t=>occurs(t,d)).sort((a,b)=>(a.time||'99').localeCompare(b.time||'99'))}function dayRoutines(d){return routines.filter(r=>(r.days||[]).includes(d.getDay())).sort((a,b)=>r.start.localeCompare(b.start))}function checked(x,d){return !!done[key(d)+'|'+x.id]}function setCheck(x,d,v){const k=key(d)+'|'+x.id;v?done[k]=true:delete done[k];save()}
function taskRow(t,d,editable=false){return '<div class="task '+(checked(t,d)?'done':'')+'"><input type="checkbox" data-check="'+t.id+'" '+(checked(t,d)?'checked':'')+' aria-label="Tandai selesai"><i class="dot" style="background:'+colors[t.category]+'"></i><div><strong>'+esc(t.title)+'</strong><small>'+(t.time||'Tanpa waktu')+' · '+esc(t.category)+'</small></div>'+(editable?'<div class="mini-actions"><button class="mini" data-edit-task="'+t.id+'" aria-label="Edit"><span class="mi" aria-hidden="true">edit</span></button><button class="mini danger" data-del-task="'+t.id+'" aria-label="Hapus"><span class="mi" aria-hidden="true">delete</span></button></div>':'<span></span>')+'</div>'}
function routineRow(r,d,editable=false){return '<div class="task '+(checked(r,d)?'done':'')+'"><input type="checkbox" data-rcheck="'+r.id+'" '+(checked(r,d)?'checked':'')+' aria-label="Tandai selesai"><i class="dot" style="background:var(--accent)"></i><div><strong>'+esc(r.title)+'</strong><small>'+r.start+'–'+r.end+'</small></div>'+(editable?'<button class="mini danger" data-del-routine="'+r.id+'" aria-label="Hapus"><span class="mi" aria-hidden="true">delete</span></button>':'<span></span>')+'</div>'}
function empty(a,b){return '<div class="empty"><strong>'+a+'</strong>'+b+'</div>'}function iconsNow(){}
function renderToday(){const ts=dayTasks(date),rs=dayRoutines(date),cats=['Sekolah','Konten','Rumah'];$('#dayName').textContent=date.toLocaleDateString('id-ID',{weekday:'long'});$('#dateLabel').textContent=date.toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'});$('#categories').innerHTML=cats.map(c=>'<button class="category '+(filter===c?'active':'')+'" data-cat="'+c+'"><span class="mi" aria-hidden="true">'+icons[c]+'</span><strong>'+c+'</strong><small>'+ts.filter(t=>t.category===c).length+' tugas</small></button>').join('');const shown=filter?ts.filter(t=>t.category===filter):ts;$('#scheduledTitle').textContent=filter||'Tugas terjadwal';$('#scheduledCount').textContent=shown.length+' tugas';$('#todayTasks').innerHTML=shown.length?shown.map(t=>taskRow(t,date)).join(''):empty('Tidak ada tugas','Pilih kategori lain atau tambah dari menu Tugas.');$('#routineCount').textContent=rs.length+' kegiatan';$('#todayRoutines').innerHTML=rs.length?rs.map(r=>routineRow(r,date)).join(''):empty('Tidak ada jadwal harian','Tambahkan dari menu Harian.');const all=[...ts,...rs],n=all.filter(x=>checked(x,date)).length;$('#progressText').textContent=n+' dari '+all.length;$('#progressFill').style.width=(all.length?n/all.length*100:0)+'%';iconsNow()}
function renderCalendar(){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate();$('#monthTitle').textContent=month.toLocaleDateString('id-ID',{month:'long',year:'numeric'});let h='';for(let i=0;i<first;i++)h+='<span class="day blank"></span>';for(let n=1;n<=last;n++){const d=new Date(y,m,n),count=dayTasks(d).length,dots='<span class="dots">'+Array(Math.min(count,3)).fill('<i></i>').join('')+'</span>';h+='<button class="day '+(key(d)===key(new Date())?'today ':'')+(key(d)===key(date)?'selected ':'')+(d.getDay()===0?'sun':'')+'" data-cal="'+key(d)+'"><b>'+n+'</b>'+dots+'</button>'}$('#calendarDays').innerHTML=h;const ts=dayTasks(date);$('#calTaskTitle').textContent='Tugas · '+date.toLocaleDateString('id-ID',{day:'numeric',month:'long'});$('#calTaskCount').textContent=ts.length+' tugas';$('#calTasks').innerHTML=ts.length?ts.map(t=>taskRow(t,date)).join(''):empty('Tidak ada tugas','Pilih tanggal lain.');iconsNow()}
function renderLists(){$('#taskList').innerHTML=tasks.length?tasks.map(t=>'<article class="list-card"><i class="dot" style="background:'+colors[t.category]+'"></i><div><h3>'+esc(t.title)+'</h3><p>'+esc(t.category)+' · '+(t.date?parse(t.date).toLocaleDateString('id-ID',{day:'numeric',month:'short'}):(t.days||[]).join(', '))+' · '+(t.time||'Tanpa waktu')+'</p></div><div class="mini-actions"><button class="mini" data-edit-task="'+t.id+'"><span class="mi" aria-hidden="true">edit</span></button><button class="mini danger" data-del-task="'+t.id+'"><span class="mi" aria-hidden="true">delete</span></button></div></article>').join(''):empty('Belum ada tugas','Tekan tombol tambah untuk membuat tugas.');$('#routineList').innerHTML=routines.length?routines.map(r=>'<article class="list-card"><i class="dot" style="background:var(--accent)"></i><div><h3>'+esc(r.title)+'</h3><p>'+r.start+'–'+r.end+' · '+r.days.length+' hari</p></div><button class="mini danger" data-del-routine="'+r.id+'"><span class="mi" aria-hidden="true">delete</span></button></article>').join(''):empty('Belum ada jadwal harian','Tekan tombol tambah untuk membuat rutinitas.');$('#noteList').innerHTML=notes.length?notes.map(n=>'<article class="list-card"><i class="dot" style="background:var(--accent)"></i><div><h3>'+esc(n.title)+'</h3><p>'+esc(n.content||'Catatan kosong')+'</p></div><button class="mini danger" data-del-note="'+n.id+'"><span class="mi" aria-hidden="true">delete</span></button></article>').join(''):empty('Belum ada catatan','Tekan tombol tambah untuk menulis catatan.');iconsNow()}
function render(){renderToday();renderCalendar();renderLists()}
function showPage(p){page=p;$$('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+p));$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#fab').hidden=!['tasks','routines','notes'].includes(p);$('#fab').textContent=p==='tasks'?'+ Tambah tugas':p==='routines'?'+ Tambah harian':'+ Tambah catatan';if(p==='calendar')renderCalendar();iconsNow()}
function openModal(id){$('#'+id).classList.add('open');$('#'+id).setAttribute('aria-hidden','false')}function closeModal(id){$('#'+id).classList.remove('open');$('#'+id).setAttribute('aria-hidden','true')}
$$('.nav-btn').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('#categories').onclick=e=>{const b=e.target.closest('[data-cat]');if(b){filter=filter===b.dataset.cat?null:b.dataset.cat;renderToday()}};$('#prevDay').onclick=()=>{date.setDate(date.getDate()-1);filter=null;renderToday()};$('#nextDay').onclick=()=>{date.setDate(date.getDate()+1);filter=null;renderToday()};$('#datePick').onclick=()=>{month=new Date(date.getFullYear(),date.getMonth(),1);showPage('calendar')};$('#prevMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);renderCalendar()};$('#nextMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);renderCalendar()};$('#calendarDays').onclick=e=>{const b=e.target.closest('[data-cal]');if(b){date=parse(b.dataset.cal);renderCalendar()}};
function checkHandler(e){if(e.target.dataset.check){const t=tasks.find(x=>x.id===e.target.dataset.check);if(t)setCheck(t,date,e.target.checked)}if(e.target.dataset.rcheck){const r=routines.find(x=>x.id===e.target.dataset.rcheck);if(r)setCheck(r,date,e.target.checked)}renderToday();if(page==='calendar')renderCalendar()}['todayTasks','todayRoutines','calTasks'].forEach(id=>$('#'+id).onchange=checkHandler);
$('#routineDays').innerHTML=['Sen','Sel','Rab','Kam','Jum','Sab','Min'].map((n,i)=>'<label class="daycheck"><input type="checkbox" value="'+([1,2,3,4,5,6,0][i])+'"><span>'+n+'</span></label>').join('');
$('#fab').onclick=()=>{if(page==='tasks'){editTask=null;$('#taskForm').reset();$('#taskDate').value=key(date);openModal('taskModal')}else if(page==='routines'){$('#routineForm').reset();openModal('routineModal')}else{$('#noteForm').reset();openModal('noteModal')}};$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$('#allDays').onclick=()=>$$('#routineDays input').forEach(x=>x.checked=true);
$('#taskForm').onsubmit=e=>{e.preventDefault();const data={id:editTask||id(),title:$('#taskName').value.trim(),category:$('#taskCategory').value,date:$('#taskDate').value,time:$('#taskTime').value,kind:'once',days:[]},i=tasks.findIndex(x=>x.id===editTask);i<0?tasks.push(data):tasks[i]=data;save();closeModal('taskModal');render();toast('Tugas disimpan')};
$('#routineForm').onsubmit=e=>{e.preventDefault();const days=$$('#routineDays input:checked').map(x=>Number(x.value));if(!days.length)return toast('Pilih minimal satu hari');if($('#routineEnd').value<=$('#routineStart').value)return toast('Jam selesai harus setelah jam mulai');routines.push({id:id(),title:$('#routineName').value.trim(),start:$('#routineStart').value,end:$('#routineEnd').value,days});save();closeModal('routineModal');render();toast('Jadwal harian disimpan')};
$('#noteForm').onsubmit=e=>{e.preventDefault();notes.unshift({id:id(),title:$('#noteTitle').value.trim(),content:$('#noteContent').value.trim()});save();closeModal('noteModal');renderLists();toast('Catatan disimpan')};
document.onclick=e=>{const edit=e.target.closest('[data-edit-task]'),dt=e.target.closest('[data-del-task]'),dr=e.target.closest('[data-del-routine]'),dn=e.target.closest('[data-del-note]');if(edit){const t=tasks.find(x=>x.id===edit.dataset.editTask);editTask=t.id;$('#taskName').value=t.title;$('#taskCategory').value=t.category;$('#taskDate').value=t.date;$('#taskTime').value=t.time;openModal('taskModal')}if(dt&&confirm('Hapus tugas ini?')){tasks=tasks.filter(x=>x.id!==dt.dataset.delTask);save();render()}if(dr&&confirm('Hapus jadwal harian ini?')){routines=routines.filter(x=>x.id!==dr.dataset.delRoutine);save();render()}if(dn&&confirm('Hapus catatan ini?')){notes=notes.filter(x=>x.id!==dn.dataset.delNote);save();renderLists()}};
const savedTheme=localStorage.getItem('taskku_theme');if(savedTheme==='dark')document.documentElement.classList.add('dark');$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('dark');localStorage.setItem('taskku_theme',document.documentElement.classList.contains('dark')?'dark':'light');$('#themeBtn').innerHTML='<span class="mi" aria-hidden="true">'+(document.documentElement.classList.contains('dark')?'light_mode':'dark_mode')+'</span>';iconsNow()};
cloud.get().then(s=>{if(s.exists){const d=s.data();applying=true;tasks=d.tasks||tasks;routines=d.routines||routines;done=d.done||done;notes=d.notes||notes;local();applying=false;render()}else cloud.set({tasks,routines,done,notes});cloudReady=true;$('#syncText').textContent='Tersinkron Firebase';cloud.onSnapshot(x=>{if(!x.exists||x.metadata.hasPendingWrites)return;const d=x.data();applying=true;tasks=d.tasks||[];routines=d.routines||[];done=d.done||{};notes=d.notes||[];local();applying=false;render()})}).catch(()=>{$('#syncText').textContent='Mode lokal';toast('Firebase belum terhubung')});
const installed=()=>window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);const installButton=$('#installNow');function showInstall(){if(!installed()&&sessionStorage.getItem('taskku_install_later')!=='1')$('#installAlert').classList.add('show')}function installReady(){installButton.disabled=false;installButton.textContent='Install aplikasi';$('#installCopy').textContent='Siap dipasang. Aplikasi akan masuk ke daftar aplikasi HP.'}window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;installReady();showInstall()});setTimeout(()=>{if(installed())return;if(isiOS){installButton.disabled=false;installButton.textContent='Cara install di iPhone';$('#installCopy').textContent='Pasang melalui Safari: Bagikan lalu Tambahkan ke Layar Utama.'}showInstall()},900);installButton.onclick=async()=>{if(installed())return $('#installAlert').classList.remove('show');if(installPrompt){installButton.disabled=true;installButton.textContent='Membuka installer...';installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==='accepted'){$('#installAlert').classList.remove('show')}else{installReady()}installPrompt=null;return}if(isiOS){toast('Di Safari: Bagikan lalu Tambahkan ke Layar Utama')}else{toast('Installer belum siap. Buka lewat Chrome dan tunggu sebentar.')}};$('#installLater').onclick=()=>{sessionStorage.setItem('taskku_install_later','1');$('#installAlert').classList.remove('show')};window.addEventListener('appinstalled',()=>{$('#installAlert').classList.remove('show');toast('Aplikasi berhasil diinstall')});
let sx=0;$('#datebar').onpointerdown=e=>sx=e.clientX;$('#datebar').onpointerup=e=>{const dx=e.clientX-sx;if(Math.abs(dx)>45){date.setDate(date.getDate()+(dx>0?-1:1));renderToday()}};
render();iconsNow();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
})();
